name: 'Test'
on: ['push', 'pull_request']

jobs:
  test:
    name: 'Vim ${{ matrix.vim_version }} on ${{ matrix.platform }}'
    strategy:
      matrix:
        vim_version:
          - 'head'
          - 'v8.2.0877'
        platform: ['Linux']

        include:
          - platform: 'Linux'
            os: 'ubuntu-latest'
            download: 'never'

      fail-fast: false

    runs-on: '${{ matrix.os }}'
    timeout-minutes: 10

    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/checkout@v2'
        with:
          repository: 'thinca/vim-themis'
          path: 'vim-themis'

      - name: 'Setup Vim'
        id: 'vim'
        uses: 'thinca/action-setup-vim@v1'
        with:
          vim_version: '${{ matrix.vim_version }}'
          download: '${{ matrix.download }}'
      - name: 'Show Vim version'
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: 'Run test'
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis ./test
